- targets:
    - https://cloud.linode.com
    - https://vault.bitwarden.com
    - https://github.com
  labels:
    datacenter: external
    service: cloud
- targets:
    - https://music.heyjohn.family
  labels:
    datacenter: lyh
    service: speedtest
- targets:
    - https://ui.garage.heyjohn.family
  labels:
    datacenter: lyh
    service: nas
- targets:
    - https://baremetalblog.com
  labels:
    datacenter: ord
    environment: production
    service: blog
